### ISSUE TITLE
Rework provider metadata discovery

### ISSUE THREAD

**Issue by oxisto** [csaf-sbom/kotlin-csaf#48]
We need to check our discovery of provider metadata again.

According to the [standard 7.3.1](https://docs.oasis-open.org/csaf/csaf/v2.0/os/csaf-v2.0-os.html#731-finding-provider-metadatajson), checking the security.txt SHOULD be performed even if the wellKnownPath provides a result. Also need to try the validation of each discovered provider-metadata and then move to the next step if one fails.

_Originally posted by @KuechA in https://github.com/csaf-sbom/kotlin-csaf/pull/35#discussion_r1787510862_

**Comment by milux** [comment]
[Section 7.1.8](https://docs.oasis-open.org/csaf/csaf/v2.0/os/csaf-v2.0-os.html#718-requirement-8-securitytxt) states that "It is possible to advertise more than one provider-metadata.json by adding multiple CSAF fields [...] However, **this SHOULD NOT be done and removed as soon as possible.**, plus "**If one of the URLs fulfills requirement 9, this MUST be used as the first CSAF entry in the security.txt.**"

That means, if we do not evaluate more than one valid Provider, then the first `CSAF` entry in `security.txt` is guaranteed to be identical to the `.well-known` URL, hence resolution of `security.txt` in that case is useless **unless** we want to change our API such that it may resolve multiple `Provider`s from an input URL.
