### ISSUE TITLE
Test inclusion

### ISSUE THREAD

**Issue by tschmidtb51** [csaf-sbom/kotlin-csaf#80]
I didn't check the code completely, so my question is: Would you detect new test file provided by the OASIS TC? And if so, please state how its done and evaluate whether/where that should be documented...

**Comment by oxisto** [comment]
> I didn't check the code completely, so my question is: Would you detect new test file provided by the OASIS TC? And if so, please state how its done and evaluate whether/where that should be documented...

Not automatically. We follow the same approach as https://github.com/secvisogram/secvisogram/tree/main/csaf-validator-lib, by using the https://github.com/oasis-tcs/csaf as a git submodule. 

There are basically two things to consider:
- We are always pulling in the latest version of the csaf repo when we build, so if a test file would *change* (I don't know if this "allowed"), we would see it in the next CI run and can see whether our expected tests change
- If new test files are added, we would need to manually include them in our unit tests. This is needed because while we know the "outcome" good or bad of a test, we do not know the expected failure cause just by looking at the JSON, so this needs some manual effort.

It's probably best to document this in a CONTRIBUTING.md or similar. I have not seen it how it is documented in secvisogram unfortunately.

**Comment by oxisto** [comment]
Update: It seems secvisogram does not take the JSON files from the TC repo (unless I am confused by their code). We actually do that, we thought this was the cleaner approach. We only add specific manual tests for some hard-to-reach branches

Example:
https://github.com/csaf-sbom/kotlin-csaf/blob/9cd3222312056e483d5db9cc67ae25ce5b40618d/csaf-validation/src/test/kotlin/io/github/csaf/sbom/validation/tests/TestsTest.kt#L67-L76

The `mandatoryTest("6-1-03-01"))` resolves into the JSON file residing in `csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-03-01.json` (https://github.com/oasis-tcs/csaf/blob/395fbfea077ca05d663c7dc930850ae18f40e936/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-03-01.json)

**Comment by tschmidtb51** [comment]
> Update: It seems secvisogram does not take the JSON files from the TC repo (unless I am confused by their code). 

The implementation of the tests is done in [secvisogram/csaf-validator-lib](https://github.com/secvisogram/csaf-validator-lib) and yes they do not document that they use the OASIS provided test files. Also, they just bump the csaf submodule during the usual dependency updates.

> We actually do that, we thought this was the cleaner approach. We only add specific manual tests for some hard-to-reach branches

It is and it is exactly what the files where build for. The csaf-validator-lib also adds some historic cases that might now be present in the repo (as some of their test files might be older than the corresponding ones in the OASIS repo).

**Comment by oxisto** [comment]
> > Update: It seems secvisogram does not take the JSON files from the TC repo (unless I am confused by their code).
> 
> The implementation of the tests is done in [secvisogram/csaf-validator-lib](https://github.com/secvisogram/csaf-validator-lib) and yes they do not document that they use the OASIS provided test files. Also, they just bump the csaf submodule during the usual dependency updates.
> 
> > We actually do that, we thought this was the cleaner approach. We only add specific manual tests for some hard-to-reach branches
> 
> It is and it is exactly what the files where build for. The csaf-validator-lib also adds some historic cases that might now be present in the repo (as some of their test files might be older than the corresponding ones in the OASIS repo).

I wonder whether it is somehow possible to encode „why“ a certain test file is supposed to fail. Probably something to discuss in the TC repo.

We could then use this information to model our failure string and basically achieve complete automated testing of the tests by just iterating through the json files corresponding to the test and potentially also picking up new files automatically.

**Comment by tschmidtb51** [comment]
> - We are always pulling in the latest version of the csaf repo when we build, so if a test file would change (I don't know if this "allowed"), we would see it in the next CI run and can see whether our expected tests change

In general, the test files are stable - unless we detect a bug.

> - If new test files are added, we would need to manually include them in our unit tests. This is needed because while we know the "outcome" good or bad of a test, we do not know the expected failure cause just by looking at the JSON, so this needs some manual effort.

Do you have a way to detect that there are new test files?

> It's probably best to document this in a CONTRIBUTING.md or similar. I have not seen it how it is documented in secvisogram unfortunately.

I would potentially put that into a DEVELOPMENT.md
The csaf-validator-lib is an open source project - feel free to suggest that.

**Comment by oxisto** [comment]
> > * We are always pulling in the latest version of the csaf repo when we build, so if a test file would change (I don't know if this "allowed"), we would see it in the next CI run and can see whether our expected tests change
> 
> In general, the test files are stable - unless we detect a bug.
> 
> > * If new test files are added, we would need to manually include them in our unit tests. This is needed because while we know the "outcome" good or bad of a test, we do not know the expected failure cause just by looking at the JSON, so this needs some manual effort.
> 
> Do you have a way to detect that there are new test files?

This might be possible with a combination of automatically updating the csaf repo (eg. with dependabot and a check within the unit test whether all 6-1-x-yy.json files that are present were parsed during the unit test. This would then „fail“ the unit test if new test files are present. This could be feasible.

**Comment by tschmidtb51** [comment]
> I wonder whether it is somehow possible to encode „why“ a certain test file is supposed to fail in the test file itself. Probably something to discuss in the TC repo.

Not in the test file. However, there is a [list of test files](https://github.com/oasis-tcs/csaf/blob/master/csaf_2.0/test/validator/data/testcases.json) that could be extended. I guess that could list the paths that result in the error and the corresponding messages.

**Comment by oxisto** [comment]
> > I wonder whether it is somehow possible to encode „why“ a certain test file is supposed to fail in the test file itself. Probably something to discuss in the TC repo.
> 
> Not in the test file. However, there is a [list of test files](https://github.com/oasis-tcs/csaf/blob/master/csaf_2.0/test/validator/data/testcases.json) that could be extended. I guess that could list the paths that result in the error and the corresponding messages.

That would be a very cool feature!

**Comment by tschmidtb51** [comment]
> > > I wonder whether it is somehow possible to encode „why“ a certain test file is supposed to fail in the test file itself. Probably something to discuss in the TC repo.
> > 
> > 
> > Not in the test file. However, there is a [list of test files](https://github.com/oasis-tcs/csaf/blob/master/csaf_2.0/test/validator/data/testcases.json) that could be extended. I guess that could list the paths that result in the error and the corresponding messages.
> 
> That would be a very cool feature!

This is not a priority right now for the editors - but that doesn't mean that you can't open an issue for that.

**Comment by oxisto** [comment]
> > > > I wonder whether it is somehow possible to encode „why“ a certain test file is supposed to fail in the test file itself. Probably something to discuss in the TC repo.
> > > 
> > > 
> > > Not in the test file. However, there is a [list of test files](https://github.com/oasis-tcs/csaf/blob/master/csaf_2.0/test/validator/data/testcases.json) that could be extended. I guess that could list the paths that result in the error and the corresponding messages.
> > 
> > 
> > That would be a very cool feature!
> 
> This is not a priority right now for the editors - but that doesn't mean that you can't open an issue for that.

Done. https://github.com/oasis-tcs/csaf/issues/820
