### ISSUE TITLE
Implement Test 6.1.11 - Correct CWE

### ISSUE THREAD

**Issue by oxisto** [csaf-sbom/kotlin-csaf#81]
This is a bit tricky because we actually would need a list of CWE identifiers and they change over time. In the secvisogram there seems to be a static list of CWEs. 

What is the expectation here @mschusterbsi @tschmidtb51 ? Unfortunately, I have not seen a GitHub repository or similar with the current CWEs, but there seems to be a XML/CSV download

**Comment by tschmidtb51** [comment]
Secvisogram uses a the CWE list provided by the csaf-validator-lib. That one is updated whenever a new CWE version is provided using a [script](https://github.com/secvisogram/csaf-validator-lib/blob/main/scripts/cwe-importCatalogue.js).

Expectation:
- Use the [current latest version](https://cwe.mitre.org/data/xml/cwec_latest.xml.zip) and generate your list from there.
- Provide a script to do so (that can be executed by a maintainer).
- Optionally: Setup a workflow to automatically open a PR that uses the script to update the CWE list.

**Comment by tschmidtb51** [comment]
Note: Only import weakness IDs - not categories or views.
