### ISSUE TITLE
Implement Test 6.1.12 - Languages

### ISSUE THREAD

**Issue by oxisto** [csaf-sbom/kotlin-csaf#82]
Needs to be a valid language, unfortunately, no standard is mentioned, I assume that https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes is meant.

**Comment by tschmidtb51** [comment]
The reference you are looking for is defined: https://docs.oasis-open.org/csaf/csaf/v2.0/os/csaf-v2.0-os.html#3216-document-property---language

Same as in #81 applies: Please provide a script to update the list.

**Comment by oxisto** [comment]
> The reference you are looking for is defined: https://docs.oasis-open.org/csaf/csaf/v2.0/os/csaf-v2.0-os.html#3216-document-property---language
> 
> Same as in [#81](https://github.com/csaf-sbom/kotlin-csaf/issues/81) applies: Please provide a script to update the list.

Thanks, I gathered that from the secvisogram implementation as well. I decided to use the JVM implementation of locale, which uses BCP 47 so this should be "auto-updated".
